/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hp_knowlgdemo_ui_NDKActivity */

#ifndef _Included_com_example_hp_knowlgdemo_ui_NDKActivity
#define _Included_com_example_hp_knowlgdemo_ui_NDKActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hp_knowlgdemo_ui_NDKActivity
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hp_knowlgdemo_ui_NDKActivity_getStringFromC
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_example_hp_knowlgdemo_ui_NDKActivity_getStringFromB
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
